### PR TITLE
Optimalization and unit test form BitcoinTransactionElement reader

### PR DESCRIPTION
**Pull request by elek**
* Unit test for transaction element reader
* Optimization and fixes (calculate the bitcoin hash and transaction hash only once)

### CODE REVIEW

**Comment by jornfranke** [comment]
thank you a lot. Before i release, can you please add in the headers of the files that you created your name instead of mine and add your name please to the one that you modified (e.g. BitcoinUtil and the test classes).

**Comment by elek** [comment]
Sorry, I missed this comment, and as I see you have already did it. Sorry again.

 Here is my experiment: https://github.com/elek/bitcoin-spark, but currently I am wondering if it faster to parse the blockchain first to hbase and do spark jobs on top of the hbased data (https://github.com/elek/bitcoin-to-hbase) Uploading to hbase takes a few hours (bulk put without WAL, writing directly the hbase file format would be faster, unfortunatelly your library uses the old mapred API and the HBase writer uses the new mapreduce one).

**Comment by jornfranke** [comment]
Hi,

thank you. I will note it do upgrade to the new API. Should not be so difficult. 
Depending on your analysis, you can also convert the blockchain data to ORC or Parquet and then do queries on it. 
The main point of the library is to extract the data. Of course you can query it, but the Bitcoin format is not designed for this. Hence you need to extract and convert it to an appropriate format.

best regards

**Comment by jornfranke** [comment]
In 1.0.3 you will be able to use both APIs via mapred.* (original API) mapreduce.* ("new" API)

**Comment by elek** [comment]
Very great. 

Just an other question. I also have a plan to analyze ethereum blockchain. I am just wondering about the easiest approach. With calling the ethereum daemon on RPC and storing the results in hbase (or in parquest file) it could be easier to debug laster (for example if some reports wrong, a random access to a specified block could be very helpfull). 

Do you have any measurement if the reading of the row block files are faster than using bitcoind rpc? 

And do you have a good solution to synchronize the new bitcoin block files directory to the hdfs? What I tried is using distcp -update, but I am thinking about to write a simple utility which uploads only the files where the modification date is newer then a specified date.

**Comment by jornfranke** [comment]
Not sure what is faster. It depends also how reliable the Ethereum daemon is. You might loose some packages, You need to update the daemon etc. Of course it can make sense in your use cases. You might develop a flume source instead of a fileformat then.

I have no measurement if it is faster, but the idea of this format is to be able to extract any bitcoin data at any time directly from HDFS, ie following an ELT approach. You can load/transform them to any destination (parquet, orc, spark processing etc.), whatever makes sense.

The scope are here more fileformats. I plan an Ethereum fileformat without depending on external libraries, so it is easier to maintain in operations. Not sure yet when it will come out.

**Pull request merged**
